/* ════════════════════════════════════════════════════════════════════
   Careers dataset.

   companies[]  — `rank` 1..10 = the current largest companies (by market cap,
                  July 2026) shown in the "Top recruiters" grid. All companies
                  (ranked + unranked) feed the university-destination estimator,
                  so students from less-elite universities still get realistic,
                  reachable employers (Big-4, Accenture, regional banks, etc.).

   Per company: sector, HQ country/city, `domain` (real logo via Clearbit),
   `salary` (approx early-career pay), `sel` (selectivity 0..1), `pre`
   (prestige bias 0..1), degrees, roles, feeder unis, about, perks.

   Curated from public graduate-recruiting patterns & company data. Figures are
   approximate guidance, not a guarantee. Remove careers_* files to undo.
   ════════════════════════════════════════════════════════════════════ */
window.CAREERS = {
  companies: [
    // ── Top 10 by market cap (July 2026) ──
    { rank: 1, name: 'NVIDIA', sector: 'AI & Semiconductors', color: '#76B900', domain: 'nvidia.com', country: 'USA', city: 'Santa Clara', salary: '≈ $145k', sel: 0.90, pre: 0.88, degrees: ['Computer Science', 'Electrical Engineering', 'Machine Learning', 'Computer Engineering'], roles: ['Deep Learning Engineer', 'Chip Design Engineer', 'Software Engineer'], unis: ['Stanford University', 'MIT', 'UC Berkeley', 'Carnegie Mellon University', 'ETH Zurich', 'Georgia Tech', 'University of Cambridge', 'Tsinghua University'], about: 'The company powering the AI boom — designs the GPUs behind modern machine learning and data centres.', perks: ['At the centre of the AI revolution', 'Elite pay & fast-growing stock', 'Deep-tech, research-heavy work'] },
    { rank: 2, name: 'Apple', sector: 'Consumer Electronics', color: '#111111', domain: 'apple.com', country: 'USA', city: 'Cupertino', salary: '≈ $135k', sel: 0.84, pre: 0.82, degrees: ['Computer Science', 'Electrical Engineering', 'Design'], roles: ['Software Engineer', 'Hardware Engineer', 'Product Designer'], unis: ['Stanford University', 'MIT', 'UC Berkeley', 'Georgia Tech', 'TU Munich', 'University of Cambridge'], about: 'The world’s most valuable consumer brand — hardware, software and services built to an obsessive standard.', perks: ['Ship products used by billions', 'Strong design & privacy culture', 'Premium pay and benefits'] },
    { rank: 3, name: 'Alphabet (Google)', sector: 'Internet & AI', color: '#4285F4', domain: 'google.com', country: 'USA', city: 'Mountain View', salary: '≈ $150k', sel: 0.86, pre: 0.86, degrees: ['Computer Science', 'Machine Learning', 'Mathematics', 'Engineering'], roles: ['Software Engineer', 'ML Engineer', 'Product Manager'], unis: ['MIT', 'Stanford University', 'Carnegie Mellon University', 'University of Cambridge', 'UC Berkeley', 'University of Waterloo'], about: 'Search, Android, Cloud and DeepMind — one of the broadest engineering playgrounds on earth.', perks: ['World-class engineering culture', 'Huge scope & internal mobility', 'Famous perks & compensation'] },
    { rank: 4, name: 'Microsoft', sector: 'Software & Cloud', color: '#00A4EF', domain: 'microsoft.com', country: 'USA', city: 'Redmond', salary: '≈ $130k', sel: 0.72, pre: 0.66, degrees: ['Computer Science', 'Engineering', 'Business'], roles: ['Software Engineer', 'Program Manager', 'Cloud Engineer'], unis: ['University of Washington', 'MIT', 'Carnegie Mellon University', 'University of Waterloo', 'Imperial College London', 'IIT Bombay'], about: 'Azure cloud, Windows, Office and GitHub — a stable giant investing heavily in AI (OpenAI partner).', perks: ['Great work-life balance', 'Strong new-grad programs', 'Broad, stable career paths'] },
    { rank: 5, name: 'Amazon', sector: 'E-commerce & Cloud', color: '#FF9900', domain: 'amazon.com', country: 'USA', city: 'Seattle', salary: '≈ $140k', sel: 0.60, pre: 0.52, degrees: ['Computer Science', 'Engineering', 'Business', 'Operations'], roles: ['Software Dev Engineer', 'Operations Manager', 'Business Analyst'], unis: ['University of Washington', 'Carnegie Mellon University', 'Georgia Tech', 'University of Waterloo', 'University of Manchester', 'IIT Delhi'], about: 'AWS, retail and logistics at planetary scale — hires huge numbers of graduates every year.', perks: ['Hires at massive scale', 'Ownership from day one', 'Strong exit reputation'] },
    { rank: 6, name: 'TSMC', sector: 'Semiconductor Manufacturing', color: '#E30613', domain: 'tsmc.com', country: 'Taiwan', city: 'Hsinchu', salary: '≈ $70k', sel: 0.80, pre: 0.74, degrees: ['Electrical Engineering', 'Materials Science', 'Physics', 'Chemical Engineering'], roles: ['Process Engineer', 'Device Engineer', 'R&D Engineer'], unis: ['National Taiwan University', 'Tsinghua University', 'Stanford University', 'MIT', 'KAIST', 'ETH Zurich'], about: 'The foundry that makes the world’s most advanced chips — including Apple’s and NVIDIA’s.', perks: ['The pinnacle of chip manufacturing', 'Global fabs (Taiwan, USA, Japan)', 'Deep materials & physics work'] },
    { rank: 7, name: 'Broadcom', sector: 'Semiconductors & Software', color: '#CC092F', domain: 'broadcom.com', country: 'USA', city: 'Palo Alto', salary: '≈ $130k', sel: 0.78, pre: 0.70, degrees: ['Electrical Engineering', 'Computer Science', 'Computer Engineering'], roles: ['ASIC Engineer', 'Software Engineer'], unis: ['Stanford University', 'UC Berkeley', 'UCLA', 'Georgia Tech', 'National Taiwan University'], about: 'Networking & infrastructure chips plus enterprise software (VMware) — a quiet semiconductor powerhouse.', perks: ['Strong pay in silicon design', 'Networking & data-centre focus', 'Lean, results-driven culture'] },
    { rank: 8, name: 'Tesla', sector: 'Electric Vehicles & Energy', color: '#E82127', domain: 'tesla.com', country: 'USA', city: 'Austin', salary: '≈ $115k', sel: 0.80, pre: 0.76, degrees: ['Mechanical Engineering', 'Electrical Engineering', 'Computer Science'], roles: ['Design Engineer', 'Firmware Engineer', 'Manufacturing Engineer'], unis: ['Stanford University', 'MIT', 'UC Berkeley', 'TU Munich', 'Georgia Tech', 'RWTH Aachen'], about: 'EVs, batteries, solar and robotics — fast-moving, mission-driven, famously intense.', perks: ['Real ownership & impact fast', 'Cutting-edge hardware + software', 'Mission-driven, high energy'] },
    { rank: 9, name: 'Meta Platforms', sector: 'Social Media & AI', color: '#0866FF', domain: 'meta.com', country: 'USA', city: 'Menlo Park', salary: '≈ $160k', sel: 0.80, pre: 0.80, degrees: ['Computer Science', 'Data Science', 'Engineering'], roles: ['Software Engineer', 'Data Scientist', 'Research Scientist'], unis: ['Stanford University', 'MIT', 'UC Berkeley', 'Carnegie Mellon University', 'University of Cambridge'], about: 'Facebook, Instagram, WhatsApp and heavy bets on AI and AR/VR (Reality Labs).', perks: ['Among the highest new-grad pay', 'Scale & AI research', 'Strong engineering ladder'] },
    { rank: 10, name: 'Micron Technology', sector: 'Memory Semiconductors', color: '#0072CE', domain: 'micron.com', country: 'USA', city: 'Boise', salary: '≈ $100k', sel: 0.64, pre: 0.50, degrees: ['Electrical Engineering', 'Materials Science', 'Physics'], roles: ['Process Engineer', 'Test Engineer'], unis: ['Purdue University', 'Georgia Tech', 'National Taiwan University', 'University of Michigan'], about: 'A leading maker of memory & storage (DRAM/NAND) — key to AI data-centre demand.', perks: ['More accessible than the giants', 'Global fabs & relocation', 'Solid engineering training'] },

    // ── Investment banking & finance ──
    { name: 'Goldman Sachs', sector: 'Investment Banking', color: '#6C8CBF', domain: 'goldmansachs.com', country: 'USA', city: 'New York', salary: '≈ $110k base', sel: 0.88, pre: 0.90, degrees: ['Economics', 'Finance', 'Mathematics', 'Business'], roles: ['IB Analyst', 'Trader', 'Quant Analyst'], unis: ['Harvard University', 'London School of Economics', 'University of Oxford', 'University of Pennsylvania', 'Bocconi University', 'University of Cambridge'], about: 'The most prestigious name in investment banking — brutal hours, elite exits.', perks: ['Unbeatable finance CV', 'Huge bonuses on top of base', 'Fast learning curve'] },
    { name: 'J.P. Morgan', sector: 'Banking', color: '#117ACA', domain: 'jpmorgan.com', country: 'USA', city: 'New York', salary: '≈ $100k base', sel: 0.74, pre: 0.70, degrees: ['Economics', 'Finance', 'Accounting', 'Business'], roles: ['Analyst', 'Associate'], unis: ['New York University', 'London School of Economics', 'University of Warwick', 'Bocconi University', 'University of Michigan'], about: 'The largest US bank — broad graduate programs across banking, markets and tech.', perks: ['Big, structured grad schemes', 'Many divisions to try', 'Global mobility'] },
    { name: 'Morgan Stanley', sector: 'Investment Banking', color: '#00448C', domain: 'morganstanley.com', country: 'USA', city: 'New York', salary: '≈ $105k base', sel: 0.82, pre: 0.80, degrees: ['Finance', 'Economics', 'Mathematics'], roles: ['IB Analyst', 'Quant'], unis: ['London School of Economics', 'University of Oxford', 'New York University', 'Bocconi University'], about: 'A top-tier investment bank strong in wealth management and dealmaking.', perks: ['Elite IB brand', 'Strong markets & wealth arms', 'High bonuses'] },
    { name: 'Citadel', sector: 'Hedge Fund / Quant', color: '#111111', domain: 'citadel.com', country: 'USA', city: 'Miami', salary: '≈ $200k+', sel: 0.93, pre: 0.92, degrees: ['Mathematics', 'Computer Science', 'Physics', 'Statistics'], roles: ['Quant Researcher', 'Software Engineer'], unis: ['MIT', 'University of Cambridge', 'University of Oxford', 'Stanford University', 'Carnegie Mellon University'], about: 'A leading hedge fund — arguably the highest new-grad pay anywhere, for the very best.', perks: ['Top pay in the world for grads', 'Cutting-edge quant work', 'Small, elite teams'] },
    { name: 'Barclays', sector: 'Banking', color: '#00AEEF', domain: 'barclays.com', country: 'UK', city: 'London', salary: '≈ £50k', sel: 0.58, pre: 0.50, degrees: ['Finance', 'Economics', 'Business'], roles: ['Graduate Analyst'], unis: ['University of Warwick', 'University of Manchester', 'London School of Economics', 'University of Nottingham'], about: 'A major UK bank with well-run graduate schemes across banking and markets.', perks: ['Accessible top-bank entry', 'Solid UK grad scheme', 'London finance exposure'] },
    { name: 'HSBC', sector: 'Banking', color: '#DB0011', domain: 'hsbc.com', country: 'UK', city: 'London', salary: '≈ £45k', sel: 0.48, pre: 0.40, degrees: ['Finance', 'Economics', 'Business'], roles: ['Graduate Analyst'], unis: ['University of Manchester', 'University of Warwick', 'University of Nottingham', 'University of Hong Kong'], about: 'A global bank with a strong Asia footprint and broad graduate intake.', perks: ['Global mobility (esp. Asia)', 'Broad, accessible programs', 'Stable career'] },

    // ── Consulting & professional services ──
    { name: 'McKinsey & Co.', sector: 'Consulting', color: '#0B1F2C', domain: 'mckinsey.com', country: 'USA', city: 'New York', salary: '≈ $112k', sel: 0.90, pre: 0.90, degrees: ['Business', 'Economics', 'Engineering', 'Any field'], roles: ['Business Analyst', 'Associate'], unis: ['Harvard University', 'INSEAD', 'University of Oxford', 'London Business School', 'IE University', 'Bocconi University'], about: 'The most prestigious strategy consultancy — advises the world’s biggest organisations.', perks: ['Best consulting CV', 'Exceptional exit options', 'Steep learning, top mentors'] },
    { name: 'BCG', sector: 'Consulting', color: '#177B57', domain: 'bcg.com', country: 'USA', city: 'Boston', salary: '≈ $110k', sel: 0.88, pre: 0.88, degrees: ['Business', 'Economics', 'Engineering', 'Any field'], roles: ['Associate', 'Consultant'], unis: ['Harvard University', 'INSEAD', 'University of Cambridge', 'HEC Paris', 'Bocconi University'], about: 'A top-3 strategy firm known for analytical rigour and a supportive culture.', perks: ['Elite strategy brand', 'Great training & mentorship', 'Strong exits'] },
    { name: 'Bain & Company', sector: 'Consulting', color: '#C8102E', domain: 'bain.com', country: 'USA', city: 'Boston', salary: '≈ $110k', sel: 0.88, pre: 0.87, degrees: ['Business', 'Economics', 'Any field'], roles: ['Associate Consultant'], unis: ['Harvard University', 'INSEAD', 'University of Oxford', 'Bocconi University'], about: 'A top-3 consultancy famous for its results focus and tight-knit culture.', perks: ['Best-rated culture in consulting', 'PE & strategy focus', 'Excellent exits'] },
    { name: 'Accenture', sector: 'Consulting & Technology', color: '#A100FF', domain: 'accenture.com', country: 'Ireland', city: 'Dublin', salary: '≈ $85k', sel: 0.40, pre: 0.24, degrees: ['Business', 'Computer Science', 'Engineering', 'Any field'], roles: ['Analyst', 'Technology Consultant'], unis: ['University of Manchester', 'University of Warwick', 'IE University', 'University of Toronto'], about: 'A huge tech-and-strategy consultancy that hires broadly from many universities.', perks: ['Very accessible entry', 'Tech + business exposure', 'Global projects'] },
    { name: 'Deloitte', sector: 'Professional Services', color: '#86BC25', domain: 'deloitte.com', country: 'UK', city: 'London', salary: '≈ $75k', sel: 0.46, pre: 0.24, degrees: ['Accounting', 'Business', 'Computer Science', 'Law'], roles: ['Consultant', 'Auditor', 'Tech Analyst'], unis: ['University of Warwick', 'University of Manchester', 'New York University', 'University of Toronto', 'IE University'], about: 'The largest of the “Big Four” — audit, consulting, tax and advisory, with broad grad intake.', perks: ['Recruits from most universities', 'Professional qualifications funded', 'Many career paths'] },
    { name: 'PwC', sector: 'Professional Services', color: '#D04A02', domain: 'pwc.com', country: 'UK', city: 'London', salary: '≈ $70k', sel: 0.42, pre: 0.22, degrees: ['Accounting', 'Business', 'Economics', 'Law'], roles: ['Associate', 'Auditor'], unis: ['University of Manchester', 'University of Nottingham', 'University of Warwick', 'IE University'], about: 'A Big-Four firm with one of the largest graduate schemes in the world.', perks: ['Accessible, structured entry', 'ACA/ACCA funded', 'Great first job on the CV'] },
    { name: 'EY', sector: 'Professional Services', color: '#2E2E38', domain: 'ey.com', country: 'UK', city: 'London', salary: '≈ $68k', sel: 0.42, pre: 0.22, degrees: ['Accounting', 'Business', 'Law'], roles: ['Associate'], unis: ['University of Manchester', 'University of Nottingham', 'University of Toronto'], about: 'A Big-Four firm strong in assurance, tax and consulting, hiring broadly.', perks: ['Broad recruiting', 'Qualifications funded', 'Global network'] },
    { name: 'KPMG', sector: 'Professional Services', color: '#00338D', domain: 'kpmg.com', country: 'Netherlands', city: 'Amstelveen', salary: '≈ $68k', sel: 0.42, pre: 0.22, degrees: ['Accounting', 'Business', 'Economics'], roles: ['Associate'], unis: ['University of Warwick', 'University of Manchester', 'University of Nottingham'], about: 'A Big-Four firm with accessible graduate programs across audit and advisory.', perks: ['Accessible entry', 'Funded qualifications', 'Solid grounding'] },

    // ── Broader / mid-cap technology ──
    { name: 'IBM', sector: 'Technology & Consulting', color: '#1F70C1', domain: 'ibm.com', country: 'USA', city: 'Armonk', salary: '≈ $95k', sel: 0.46, pre: 0.36, degrees: ['Computer Science', 'Engineering', 'Business'], roles: ['Software Engineer', 'Consultant'], unis: ['University of Manchester', 'Georgia Tech', 'University of Toronto', 'IIT Delhi'], about: 'A century-old tech company spanning cloud, AI (watsonx) and consulting.', perks: ['Accessible tech entry', 'Research heritage', 'Broad roles'] },
    { name: 'Intel', sector: 'Semiconductors', color: '#0071C5', domain: 'intel.com', country: 'USA', city: 'Santa Clara', salary: '≈ $105k', sel: 0.60, pre: 0.52, degrees: ['Electrical Engineering', 'Computer Science', 'Physics'], roles: ['Hardware Engineer', 'Software Engineer'], unis: ['Georgia Tech', 'Purdue University', 'Technion', 'TU Munich'], about: 'A classic chipmaker investing to regain process leadership — strong for hardware careers.', perks: ['Deep hardware engineering', 'Global fabs & R&D', 'Good work-life balance'] },
    { name: 'Oracle', sector: 'Software & Cloud', color: '#F80000', domain: 'oracle.com', country: 'USA', city: 'Austin', salary: '≈ $110k', sel: 0.50, pre: 0.44, degrees: ['Computer Science', 'Engineering'], roles: ['Software Engineer'], unis: ['University of Manchester', 'Georgia Tech', 'IIT Bombay', 'University of Waterloo'], about: 'Enterprise databases and a fast-growing cloud (OCI) business.', perks: ['Accessible SWE roles', 'Enterprise-scale systems', 'Cloud growth'] },
    { name: 'SAP', sector: 'Enterprise Software', color: '#0FAAFF', domain: 'sap.com', country: 'Germany', city: 'Walldorf', salary: '≈ €60k', sel: 0.50, pre: 0.48, degrees: ['Computer Science', 'Business Informatics', 'Engineering'], roles: ['Developer', 'Consultant'], unis: ['TU Munich', 'ETH Zurich', 'University of Mannheim', 'University of Waterloo'], about: 'Europe’s biggest software company — the backbone of enterprise business software.', perks: ['Strong in Europe', 'Great work-life balance', 'Business + tech blend'] },
    { name: 'Salesforce', sector: 'Cloud Software', color: '#00A1E0', domain: 'salesforce.com', country: 'USA', city: 'San Francisco', salary: '≈ $120k', sel: 0.58, pre: 0.54, degrees: ['Computer Science', 'Business'], roles: ['Software Engineer', 'Solutions Engineer'], unis: ['UC Berkeley', 'University of Waterloo', 'Georgia Tech'], about: 'The leading CRM cloud platform, known for a strong culture and benefits.', perks: ['Great culture & benefits', 'Cloud/SaaS experience', 'Good work-life balance'] },
    { name: 'Adobe', sector: 'Software', color: '#FA0F00', domain: 'adobe.com', country: 'USA', city: 'San Jose', salary: '≈ $125k', sel: 0.62, pre: 0.56, degrees: ['Computer Science', 'Design'], roles: ['Software Engineer', 'Product Designer'], unis: ['Carnegie Mellon University', 'UC Berkeley', 'IIT Delhi'], about: 'Creative software (Photoshop) plus a fast-growing digital-experience cloud.', perks: ['Design + engineering', 'Strong work-life balance', 'Beloved products'] },
    { name: 'Palantir', sector: 'Data & AI', color: '#101113', domain: 'palantir.com', country: 'USA', city: 'Denver', salary: '≈ $135k', sel: 0.85, pre: 0.82, degrees: ['Computer Science', 'Mathematics', 'Physics'], roles: ['Forward Deployed Engineer', 'Software Engineer'], unis: ['Stanford University', 'MIT', 'University of Cambridge', 'University of Oxford'], about: 'Data & AI platforms for governments and enterprises — intense, mission-driven.', perks: ['High impact, real problems', 'Strong pay & equity', 'Small teams, big ownership'] },
    { name: 'Stripe', sector: 'Fintech', color: '#635BFF', domain: 'stripe.com', country: 'USA', city: 'San Francisco', salary: '≈ $140k', sel: 0.80, pre: 0.76, degrees: ['Computer Science', 'Engineering'], roles: ['Software Engineer'], unis: ['University of Waterloo', 'MIT', 'Stanford University', 'University of Cambridge'], about: 'The developer-favourite payments platform powering online commerce.', perks: ['Top engineering bar', 'Great pay & equity', 'Craft-focused culture'] },
    { name: 'Spotify', sector: 'Music & Tech', color: '#1DB954', domain: 'spotify.com', country: 'Sweden', city: 'Stockholm', salary: '≈ €65k', sel: 0.60, pre: 0.56, degrees: ['Computer Science', 'Data Science', 'Design'], roles: ['Engineer', 'Data Scientist'], unis: ['KTH Royal Institute', 'University of Waterloo', 'Imperial College London'], about: 'The world’s biggest audio-streaming platform, strong in data and product.', perks: ['Great culture & flexibility', 'Data-driven product', 'European tech hub'] },
    { name: 'Booking.com', sector: 'Travel Technology', color: '#003580', domain: 'booking.com', country: 'Netherlands', city: 'Amsterdam', salary: '≈ €55k', sel: 0.55, pre: 0.50, degrees: ['Computer Science', 'Data Science', 'Business'], roles: ['Developer', 'Analyst'], unis: ['TU Delft', 'University of Manchester', 'Bocconi University'], about: 'Europe’s largest travel-tech company — huge scale in data and experimentation.', perks: ['Data & A/B testing at scale', 'International Amsterdam hub', 'Relocation support'] },

    // ── Industrial / automotive / energy ──
    { name: 'Siemens', sector: 'Industrial & Engineering', color: '#009999', domain: 'siemens.com', country: 'Germany', city: 'Munich', salary: '≈ €55k', sel: 0.45, pre: 0.44, degrees: ['Electrical Engineering', 'Mechanical Engineering', 'Computer Science'], roles: ['Engineer'], unis: ['TU Munich', 'ETH Zurich', 'RWTH Aachen', 'University of Manchester'], about: 'A European industrial giant in automation, energy and digital industries.', perks: ['Blue-chip engineering', 'Great work-life balance', 'Global projects'] },
    { name: 'Bosch', sector: 'Engineering', color: '#E20015', domain: 'bosch.com', country: 'Germany', city: 'Gerlingen', salary: '≈ €58k', sel: 0.45, pre: 0.42, degrees: ['Mechanical Engineering', 'Electrical Engineering', 'Computer Science'], roles: ['Engineer'], unis: ['TU Munich', 'RWTH Aachen', 'ETH Zurich'], about: 'The world’s largest auto-parts supplier, also strong in IoT and appliances.', perks: ['Solid engineering culture', 'Stable & employee-owned ethos', 'Great training'] },
    { name: 'BMW Group', sector: 'Automotive', color: '#16588E', domain: 'bmw.com', country: 'Germany', city: 'Munich', salary: '≈ €58k', sel: 0.50, pre: 0.50, degrees: ['Mechanical Engineering', 'Electrical Engineering', 'Design'], roles: ['Engineer', 'Designer'], unis: ['TU Munich', 'RWTH Aachen', 'ETH Zurich'], about: 'A premium carmaker at the front of the EV and software-defined-vehicle shift.', perks: ['Iconic engineering brand', 'EV & software transition', 'Strong German benefits'] },
    { name: 'Airbus', sector: 'Aerospace', color: '#00205B', domain: 'airbus.com', country: 'France', city: 'Toulouse', salary: '≈ €48k', sel: 0.55, pre: 0.55, degrees: ['Aerospace Engineering', 'Mechanical Engineering'], roles: ['Engineer'], unis: ['ISAE-SUPAERO', 'TU Munich', 'Imperial College London', 'University of Cambridge'], about: 'The world’s largest planemaker — the place for aerospace engineering in Europe.', perks: ['Top aerospace employer', 'Cutting-edge engineering', 'International sites'] },
    { name: 'Shell', sector: 'Energy', color: '#DD1D21', domain: 'shell.com', country: 'UK', city: 'London', salary: '≈ £48k', sel: 0.50, pre: 0.46, degrees: ['Chemical Engineering', 'Mechanical Engineering', 'Geoscience'], roles: ['Engineer', 'Analyst'], unis: ['Imperial College London', 'TU Delft', 'University of Manchester'], about: 'A global energy major investing in the transition to lower-carbon energy.', perks: ['Well-paid engineering', 'Global relocation', 'Energy-transition projects'] },

    // ── Consumer goods (recruit broadly) ──
    { name: 'Unilever', sector: 'Consumer Goods', color: '#1F36C7', domain: 'unilever.com', country: 'UK', city: 'London', salary: '≈ £38k', sel: 0.48, pre: 0.40, degrees: ['Business', 'Engineering', 'Marketing', 'Chemistry'], roles: ['Management Trainee'], unis: ['University of Warwick', 'University of Manchester', 'Bocconi University', 'IE University'], about: 'A consumer-goods giant (Dove, Ben & Jerry’s) famous for its leadership grad scheme.', perks: ['Prestigious UFLP grad scheme', 'Rotational leadership track', 'Sustainability focus'] },
    { name: 'Procter & Gamble', sector: 'Consumer Goods', color: '#003DA5', domain: 'pg.com', country: 'USA', city: 'Cincinnati', salary: '≈ $75k', sel: 0.55, pre: 0.48, degrees: ['Business', 'Engineering', 'Marketing'], roles: ['Brand Manager', 'Engineer'], unis: ['Bocconi University', 'University of Warwick', 'IE University', 'University of Michigan'], about: 'The classic brand-management school — Gillette, Pampers, Oral-B and more.', perks: ['Best brand-marketing training', 'Promote-from-within culture', 'Global brands'] },
    { name: 'L’Oréal', sector: 'Beauty & Consumer', color: '#111111', domain: 'loreal.com', country: 'France', city: 'Clichy', salary: '≈ €45k', sel: 0.50, pre: 0.46, degrees: ['Business', 'Marketing', 'Chemistry'], roles: ['Management Trainee'], unis: ['HEC Paris', 'Bocconi University', 'University of Warwick'], about: 'The world’s largest beauty company, strong in marketing and R&D.', perks: ['Marketing & brand careers', 'Global, fashion-forward', 'Fast progression'] },
    { name: 'Nestlé', sector: 'Consumer Goods', color: '#63A5DE', domain: 'nestle.com', country: 'Switzerland', city: 'Vevey', salary: '≈ €50k', sel: 0.44, pre: 0.36, degrees: ['Business', 'Food Science', 'Engineering'], roles: ['Graduate Trainee'], unis: ['Bocconi University', 'University of Manchester', 'University of Nottingham'], about: 'The world’s largest food & beverage company, hiring broadly across functions.', perks: ['Very accessible entry', 'Global relocation', 'Broad functions'] }
  ],

  universities: [
    { name: 'University of Oxford', short: 'Oxford', tier: 5, fields: ['Economics', 'Law', 'Medicine', 'Computer Science', 'Mathematics', 'Humanities'] },
    { name: 'University of Cambridge', short: 'Cambridge', tier: 5, fields: ['Engineering', 'Computer Science', 'Mathematics', 'Economics', 'Natural Sciences'] },
    { name: 'MIT', short: 'MIT', tier: 5, fields: ['Engineering', 'Computer Science', 'Mathematics', 'Physics', 'Business'] },
    { name: 'Stanford University', short: 'Stanford', tier: 5, fields: ['Computer Science', 'Engineering', 'Business', 'Design'] },
    { name: 'Harvard University', short: 'Harvard', tier: 5, fields: ['Economics', 'Law', 'Business', 'Medicine', 'Humanities'] },
    { name: 'London School of Economics', short: 'LSE', tier: 5, fields: ['Economics', 'Finance', 'Politics', 'Law', 'Business'] },
    { name: 'ETH Zurich', short: 'ETH', tier: 5, fields: ['Engineering', 'Computer Science', 'Physics', 'Mathematics'] },
    { name: 'Imperial College London', short: 'Imperial', tier: 4, fields: ['Engineering', 'Computer Science', 'Medicine', 'Mathematics', 'Aerospace Engineering'] },
    { name: 'Carnegie Mellon University', short: 'CMU', tier: 4, fields: ['Computer Science', 'Engineering', 'Design'] },
    { name: 'UC Berkeley', short: 'Berkeley', tier: 4, fields: ['Computer Science', 'Engineering', 'Business', 'Economics'] },
    { name: 'UCLA', short: 'UCLA', tier: 3, fields: ['Engineering', 'Computer Science', 'Business'] },
    { name: 'Bocconi University', short: 'Bocconi', tier: 4, fields: ['Economics', 'Finance', 'Business', 'Law'] },
    { name: 'INSEAD', short: 'INSEAD', tier: 5, fields: ['Business'] },
    { name: 'London Business School', short: 'LBS', tier: 5, fields: ['Business', 'Finance'] },
    { name: 'University of Pennsylvania', short: 'UPenn', tier: 4, fields: ['Business', 'Finance', 'Economics', 'Engineering'] },
    { name: 'New York University', short: 'NYU', tier: 3, fields: ['Finance', 'Business', 'Law', 'Computer Science'] },
    { name: 'University of Warwick', short: 'Warwick', tier: 4, fields: ['Economics', 'Business', 'Mathematics', 'Engineering', 'Accounting'] },
    { name: 'University of Manchester', short: 'Manchester', tier: 3, fields: ['Engineering', 'Business', 'Computer Science', 'Economics', 'Accounting'] },
    { name: 'University of Nottingham', short: 'Nottingham', tier: 3, fields: ['Business', 'Engineering', 'Economics', 'Accounting'] },
    { name: 'University of Washington', short: 'UW', tier: 3, fields: ['Computer Science', 'Engineering'] },
    { name: 'Georgia Tech', short: 'GT', tier: 3, fields: ['Engineering', 'Computer Science', 'Electrical Engineering'] },
    { name: 'Purdue University', short: 'Purdue', tier: 3, fields: ['Engineering', 'Electrical Engineering', 'Materials Science', 'Computer Science'] },
    { name: 'University of Michigan', short: 'Michigan', tier: 3, fields: ['Engineering', 'Business', 'Economics'] },
    { name: 'University of Waterloo', short: 'Waterloo', tier: 3, fields: ['Computer Science', 'Engineering'] },
    { name: 'University of Toronto', short: 'UofT', tier: 4, fields: ['Computer Science', 'Engineering', 'Business', 'Medicine'] },
    { name: 'HEC Paris', short: 'HEC', tier: 4, fields: ['Business', 'Finance'] },
    { name: 'TU Munich', short: 'TUM', tier: 4, fields: ['Engineering', 'Computer Science', 'Physics', 'Mechanical Engineering'] },
    { name: 'RWTH Aachen', short: 'RWTH', tier: 3, fields: ['Mechanical Engineering', 'Electrical Engineering', 'Engineering'] },
    { name: 'University of Mannheim', short: 'Mannheim', tier: 3, fields: ['Business', 'Economics', 'Business Informatics'] },
    { name: 'IE University', short: 'IE', tier: 3, fields: ['Business', 'Law', 'Computer Science'] },
    { name: 'Tsinghua University', short: 'Tsinghua', tier: 5, fields: ['Engineering', 'Computer Science', 'Physics'] },
    { name: 'National Taiwan University', short: 'NTU', tier: 4, fields: ['Electrical Engineering', 'Computer Science', 'Materials Science', 'Physics'] },
    { name: 'KAIST', short: 'KAIST', tier: 4, fields: ['Engineering', 'Computer Science', 'Physics'] },
    { name: 'IIT Bombay', short: 'IIT-B', tier: 4, fields: ['Engineering', 'Computer Science', 'Electrical Engineering'] },
    { name: 'IIT Delhi', short: 'IIT-D', tier: 4, fields: ['Engineering', 'Computer Science', 'Electrical Engineering'] },
    { name: 'Technion', short: 'Technion', tier: 4, fields: ['Engineering', 'Computer Science', 'Physics'] },
    { name: 'KTH Royal Institute', short: 'KTH', tier: 3, fields: ['Engineering', 'Computer Science'] },
    { name: 'TU Delft', short: 'Delft', tier: 4, fields: ['Engineering', 'Computer Science', 'Aerospace Engineering'] },
    { name: 'ISAE-SUPAERO', short: 'SUPAERO', tier: 4, fields: ['Aerospace Engineering', 'Engineering'] },
    { name: 'University of Hong Kong', short: 'HKU', tier: 3, fields: ['Business', 'Finance', 'Law', 'Medicine'] }
  ]
};
