'use strict';
/* Builds design/data/city_photos.js — one real photo per City-guide city.

   Source: each city's Wikidata "image" (P18), a single representative photo
   chosen by Wikidata editors (not a montage), served from Wikimedia Commons.
   Every entry carries the author and licence from Commons for the credit line.
   Overrides (OVERRIDE below) replace a P18 that doesn't work as a background
   (portrait crops, aerials that read as maps, coats of arms…).

     node tools/city-photos/build.js        (needs network; ~2 min, polite pacing)
*/
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const UA = 'UniVersity-city-photos/1.0 (student project; ivan.kharytonchuk10@gmail.com)';
const CITIES = JSON.parse(fs.readFileSync(path.join(__dirname, 'cities.json'), 'utf8'));
const OUT = path.join(__dirname, '..', '..', 'design', 'data', 'city_photos.js');
const COUNTRY = { gb: 'Q145', es: 'Q29', de: 'Q183', fr: 'Q142', it: 'Q38', pt: 'Q45', nl: 'Q55', se: 'Q34', ch: 'Q39', dk: 'Q35', be: 'Q31', fi: 'Q33', ie: 'Q27', ua: 'Q212', us: 'Q30' };
const LABEL = { Zurich: 'Zürich', Sevilla: 'Seville', 'New York': 'New York City', Frankfurt: 'Frankfurt am Main' };
// Hand-picked replacements, filled in after reviewing the contact sheet (file names on Commons).
const OVERRIDE = fs.existsSync(path.join(__dirname, 'overrides.json')) ? JSON.parse(fs.readFileSync(path.join(__dirname, 'overrides.json'), 'utf8')) : {};

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
async function getJSON(url) {
    for (let i = 0; i < 4; i++) {
        const r = await fetch(url, { headers: { 'User-Agent': UA, Accept: 'application/sparql-results+json, application/json' } });
        if (r.ok) return r.json();
        await sleep(1500 * (i + 1));
    }
    throw new Error('fetch failed ' + url.slice(0, 120));
}
function thumb(file, w) {
    const f = file.replace(/ /g, '_'), h = crypto.createHash('md5').update(f).digest('hex');
    return 'https://upload.wikimedia.org/wikipedia/commons/thumb/' + h[0] + '/' + h.slice(0, 2) + '/' + encodeURIComponent(f) + '/' + w + 'px-' + encodeURIComponent(f) + (/\.(tiff?|svg)$/i.test(f) ? '.jpg' : '');
}
function orig(file) {
    const f = file.replace(/ /g, '_'), h = crypto.createHash('md5').update(f).digest('hex');
    return 'https://upload.wikimedia.org/wikipedia/commons/' + h[0] + '/' + h.slice(0, 2) + '/' + encodeURIComponent(f);
}
async function p18(cc, name) {
    const label = (LABEL[name] || name).replace(/"/g, '\\"');
    const q = `SELECT ?item ?img ?links WHERE {
      { ?item rdfs:label "${label}"@en } UNION { ?item skos:altLabel "${label}"@en }
      ?item wdt:P17 wd:${COUNTRY[cc]}; wdt:P18 ?img; wikibase:sitelinks ?links.
      ?item wdt:P31/wdt:P279* wd:Q486972.
    } ORDER BY DESC(?links) LIMIT 1`;
    const d = await getJSON('https://query.wikidata.org/sparql?format=json&query=' + encodeURIComponent(q));
    const b = d.results.bindings[0];
    if (!b) return null;
    return { qid: b.item.value.split('/').pop(), file: decodeURIComponent(b.img.value.split('/').pop()).replace(/_/g, ' ') };
}
async function meta(file) {
    const d = await getJSON('https://commons.wikimedia.org/w/api.php?action=query&format=json&prop=imageinfo&iiprop=extmetadata|size&titles=' + encodeURIComponent('File:' + file));
    const pg = Object.values(d.query.pages)[0], ii = pg.imageinfo && pg.imageinfo[0];
    if (!ii) return {};
    const m = ii.extmetadata || {}, strip = (s) => String(s || '').replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim();
    return { by: strip(m.Artist && m.Artist.value).slice(0, 80), lic: strip(m.LicenseShortName && m.LicenseShortName.value), w: ii.width, h: ii.height };
}

(async () => {
    const out = {}, miss = [];
    for (const [cc, name] of CITIES) {
        try {
            let r = OVERRIDE[cc + '/' + name] ? { file: OVERRIDE[cc + '/' + name] } : await p18(cc, name);
            if (!r) { miss.push(cc + '/' + name); continue; }
            const m = await meta(r.file);
            // never ask Commons to upscale (it errors); PNG thumbnails stay PNG, so keep those smaller
            const png = /\.png$/i.test(r.file), size = (want) => (m.w && m.w <= want ? orig(r.file) : thumb(r.file, want));
            out[cc + '/' + name] = { f: r.file, s: size(png ? 330 : 500), l: size(png ? 960 : 1280), by: m.by || 'Wikimedia Commons', lic: m.lic || '', wh: m.w && m.h ? +(m.w / m.h).toFixed(2) : null };
            console.log(cc, name, '→', r.file, m.w + 'x' + m.h, m.lic);
        } catch (e) { miss.push(cc + '/' + name + ' (' + e.message + ')'); }
        await sleep(700);
    }
    fs.writeFileSync(OUT, '/* Generated by tools/city-photos/build.js — one Wikimedia Commons photo per City-guide city\n   (Wikidata P18 unless overridden). Credits: by + lic; page: commons.wikimedia.org/wiki/File:<f>. */\nwindow.CITY_PHOTOS = ' + JSON.stringify(out) + ';\n');
    console.log('\nwrote', Object.keys(out).length, 'photos; missing:', miss);
})();
